In [162]:
import pandas as pd
import numpy as np
import random
import os

In [33]:
pd.options.display.float_format = '{:,.2f}'.format

### Problema 1
Vamos praticar gerar matrizes e fazer operações com as linhas e colunas:

(a) Crie uma matriz A com as dimensões (5, 4) e elementos aleatórios variando entre 0 e 50, com o 50 incluso;

__Dica:__ Utilize as funções `np.random.randint` e `np.reshape`

(b) Retorne a média do vetor

(c) Retorne os menores valores de cada coluna;

(d) Retorne os maiores valores de cada linha.

In [12]:
random.seed(1)

In [8]:
array = np.random.randint(51,size=(5,4))

In [20]:
print(array)

[[ 3  3  9 44]
 [19 27 21 50]
 [11 41 14  6]
 [19  9  3  5]
 [ 0 30 49 46]]


In [13]:
array.mean()

20.45

In [22]:
array.min(axis=0)

array([0, 3, 3, 5])

In [17]:
array.max(axis=1)

array([44, 50, 41, 19, 49])

### Problema 2

Crie um objeto DataFrame que contenha os dados da tabela abaixo, os quais se referem ao peso, altura e idade de cinco pessoas:


| Peso (kg) | Altura (cm) | Idade (anos) |
|-----------|-------------|--------------|
|  47 | 161	| 31 |
|  80 | 170	| 21 |
|  60 | 175	| 16 |
|  90 | 162	| 28 |
| 100 | 185	| 23 |
| 147 | 189 | 32 |

Com base no DataFrame criado, realize o que for pedido nos itens abaixo:

(a) Visualize apenas os dados da coluna que contém a altura das pessoas;

(b) Obtenha a idade média das pessoas;

(c) Obtenha os dados das pessoas que estão abaixo da altura média;

(d) Crie um nova coluna no DataFrame que contenha o IMC (Índice de Massa Corporal) de cada pessoa;

__Obs.:__ A fórmula para o IMC é dada por IMC = Peso/(Altura)² com o peso em kg e a altura em metros.

(e) Remova a coluna que contém a idade das pessoas;

(f) Crie uma nova coluna chamada Classificação, que contenha a classificação de cada indivíduo, de acordo com o seu IMC. Para isso, consulte a tabela abaixo.

| IMC             | Classificação |
|-----------------|---------------|
Menor que 18,5    | Subpeso |
Entre 18,5 e 24,9 | Normal |
Entre 25,0 e 29,9 | Sobrepeso |
Entre 30,0 e 39,9 | Obesidade Grau I |
Maior que 40,0    | Obesidade Grau II |

(g) Salve esses dados do DataFrame em um arquivo csv.

In [31]:
peso,altura,idade = [47,80,60,90,100,147],[161,170,175,162,185,189],[31,21,16,28,23,32]

df = pd.DataFrame({'peso':peso,'altura':altura,'idade':idade})

df

peso  altura  idade
0    47     161     31
1    80     170     21
2    60     175     16
3    90     162     28
4   100     185     23
5   147     189     32

In [29]:
df[['altura']]

altura
0     161
1     170
2     175
3     162
4     185
5     189

In [35]:
df[['idade']].mean()

idade   25.17
dtype: float64

In [38]:
df[['altura']].mean()

altura   173.67
dtype: float64

In [39]:
mask = df['altura'] < df['altura'].mean()

df.loc[mask]

peso  altura  idade
0    47     161     31
1    80     170     21
3    90     162     28

In [52]:
df['IMC'] = df['peso'] / (df['altura']/100)**2

df

peso  altura  idade   IMC
0    47     161     31 18.13
1    80     170     21 27.68
2    60     175     16 19.59
3    90     162     28 34.29
4   100     185     23 29.22
5   147     189     32 41.15

In [54]:
df.drop('idade',axis=1,inplace=True)

In [58]:
def classifica_imc(x):
    
    if x < 18.5:
        return 'Subpeso'
    if x < 25:
        return 'Normal'
    if x < 30:
        return 'Sobrepeso'
    if x < 40:
        return 'Obesidade Grau I'
    if x > 40:
        return 'Obesidade Grau II'
    

df['Classificacao'] = df['IMC'].apply(classifica_imc)

df

peso  altura   IMC      Classificacao
0    47     161 18.13            Subpeso
1    80     170 27.68          Sobrepeso
2    60     175 19.59             Normal
3    90     162 34.29   Obesidade Grau I
4   100     185 29.22          Sobrepeso
5   147     189 41.15  Obesidade Grau II

### Problema 3

O arquivo avocado.xlsx consiste em um dataset que contém dados sobre vendas de abacates  em diversas regiões dos Estados Unidos. Essa dataset contém as seguintes colunas:

| Coluna | Descrição |
|--------|-----------|
| Date | data da observação |
| AveragePrice | preço médio de um único abacate |
| year | ano |
| region | cidade ou região da observação |
| Total Volume | volume total de abacates vendidos |

Além das informações acima, contidas no arquivo avocado.xlsx, o tipo do abacate (convencional ou orgânico) também seria uma informação importante para a sua análise. Suponhamos que você conseguiu essas informações para cada uma das observações do arquivo avocado.csv, na mesma ordem, e salvou-as no arquivo avocado_type.xlsx. Portanto, tudo o que você precisa é juntar esses dois arquivos em um mesmo DataFrame.

Com o DataFrame criado, obtenha o que é solicitado nos itens elencados abaixo:




In [76]:
df1 = pd.read_csv('data1/avocado.csv',sep=';')

df2 = pd.read_excel('data1/avocado_type.xlsx')

df_avocado = pd.concat([df1,df2],axis=1)

df_avocado

Date  AveragePrice  Total Volume  year            region  \
0      2015-12-27          1.33     64,236.62  2015            Albany   
1      2015-12-20          1.35     54,876.98  2015            Albany   
2      2015-12-13          0.93    118,220.22  2015            Albany   
3      2015-12-06          1.08     78,992.15  2015            Albany   
4      2015-11-29          1.28     51,039.60  2015            Albany   
...           ...           ...           ...   ...               ...   
18244  2018-02-04          1.63     17,074.83  2018  WestTexNewMexico   
18245  2018-01-28          1.71     13,888.04  2018  WestTexNewMexico   
18246  2018-01-21          1.87     13,766.76  2018  WestTexNewMexico   
18247  2018-01-14          1.93     16,205.22  2018  WestTexNewMexico   
18248  2018-01-07          1.62     17,489.58  2018  WestTexNewMexico   

               type  
0          orgânico  
1      convencional  
2      convencional  
3          orgânico  
4          orgânico  
...             ...  
18244  convencional  
18245  convencional  
18246  convencional  
18247  convencional  
18248  convencional  

[18249 rows x 6 columns]

(a) A quantidade de abacates do tipo convecional e do tipo orgânico.

In [77]:
df_avocado['type'].value_counts()

orgânico        9135
convencional    9114
Name: type, dtype: int64


(b) A quantidade de registros (linhas) de abacates vendidos para cada região ordenada da maior venda para a menor.

In [81]:
df_avocado.groupby('region')[['Total Volume']].sum().sort_values('Total Volume',ascending=False)[1:]

#Primeira linha era para todo território americano.


Total Volume
region                              
West                1,086,779,155.75
California          1,028,981,653.17
SouthCentral        1,011,279,618.83
Northeast             713,280,909.56
Southeast             615,238,409.11
GreatLakes            589,642,549.29
Midsouth              508,349,357.20
LosAngeles            507,896,547.63
Plains                311,188,529.11
NewYork               240,734,127.53
DallasFtWorth         208,419,286.55
Houston               203,167,867.80
PhoenixTucson         195,643,312.50
WestTexNewMexico      144,521,839.78
Denver                138,902,535.99
SanFrancisco          135,830,191.78
BaltimoreWashington   134,713,919.32
Chicago               133,702,338.51
Portland              110,552,211.60
Seattle               109,214,177.96
MiamiFtLauderdale      97,673,224.03
Boston                 97,273,984.83
SanDiego               89,791,919.69
Atlanta                88,605,118.85
Sacramento             75,163,746.86
Philadelphia           71,838,798.18
NorthernNewEngland     71,532,894.11
Tampa                  66,004,539.31
Detroit                63,422,419.38
SouthCarolina          60,753,772.90
Orlando                58,660,703.89
LasVegas               54,376,906.40
HartfordSpringfield    50,670,537.46
RaleighGreensboro      48,202,731.66
NewOrleansMobile       45,695,136.58
CincinnatiDayton       44,522,007.57
RichmondNorfolk        42,230,851.45
HarrisburgScranton     41,808,858.68
Nashville              35,612,089.23
Charlotte              35,555,544.42
StLouis                32,072,833.33
Indianapolis           30,263,391.43
GrandRapids            30,211,735.93
Columbus               29,993,361.42
Jacksonville           28,790,004.74
Roanoke                25,042,010.81
BuffaloRochester       22,962,470.40
Pittsburgh             18,806,345.81
Louisville             16,097,002.40
Albany                 16,067,799.97
Spokane                15,565,275.48
Boise                  14,413,187.75
Syracuse               10,942,667.68

(c) Para que todos os labels das colunas fiquem padronizados, renomeie aqueles que estão iniciando em letra minúscula para que iniciem em letra maiúscula, trocando espaço por _ e adicionando _ como separação de texto.

In [94]:
df_avocado.columns = df_avocado.columns.str.lower()

df_avocado.rename({'averageprice':'average_price', 'total volume':'total_volume'},inplace=True,axis=1)

df_avocado

date  average_price  total_volume  year            region  \
0      2015-12-27           1.33     64,236.62  2015            Albany   
1      2015-12-20           1.35     54,876.98  2015            Albany   
2      2015-12-13           0.93    118,220.22  2015            Albany   
3      2015-12-06           1.08     78,992.15  2015            Albany   
4      2015-11-29           1.28     51,039.60  2015            Albany   
...           ...            ...           ...   ...               ...   
18244  2018-02-04           1.63     17,074.83  2018  WestTexNewMexico   
18245  2018-01-28           1.71     13,888.04  2018  WestTexNewMexico   
18246  2018-01-21           1.87     13,766.76  2018  WestTexNewMexico   
18247  2018-01-14           1.93     16,205.22  2018  WestTexNewMexico   
18248  2018-01-07           1.62     17,489.58  2018  WestTexNewMexico   

               type  
0          orgânico  
1      convencional  
2      convencional  
3          orgânico  
4          orgânico  
...             ...  
18244  convencional  
18245  convencional  
18246  convencional  
18247  convencional  
18248  convencional  

[18249 rows x 6 columns]

(d) Essa dado possui duplicados? Se sim, remova-os do dataset.

In [96]:
df_avocado.duplicated().sum()

0

(e) Retire dos dados a região 'TotalUS'

In [103]:
df_avocado = df_avocado.loc[df_avocado['region']!='TotalUS']

<class 'pandas.core.frame.DataFrame'>
Int64Index: 17911 entries, 0 to 18248
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   date           17911 non-null  object 
 1   average_price  17911 non-null  float64
 2   total_volume   17911 non-null  float64
 3   year           17911 non-null  int64  
 4   region         17911 non-null  object 
 5   type           17911 non-null  object 
dtypes: float64(2), int64(1), object(3)
memory usage: 979.5+ KB


(g) Apresente as regiões que mais venderam abacate em todo o período em ordem decrescente.

In [105]:
df_avocado.groupby('region')[['total_volume']].sum().sort_values('total_volume',ascending=False)

total_volume
region                              
West                1,086,779,155.75
California          1,028,981,653.17
SouthCentral        1,011,279,618.83
Northeast             713,280,909.56
Southeast             615,238,409.11
GreatLakes            589,642,549.29
Midsouth              508,349,357.20
LosAngeles            507,896,547.63
Plains                311,188,529.11
NewYork               240,734,127.53
DallasFtWorth         208,419,286.55
Houston               203,167,867.80
PhoenixTucson         195,643,312.50
WestTexNewMexico      144,521,839.78
Denver                138,902,535.99
SanFrancisco          135,830,191.78
BaltimoreWashington   134,713,919.32
Chicago               133,702,338.51
Portland              110,552,211.60
Seattle               109,214,177.96
MiamiFtLauderdale      97,673,224.03
Boston                 97,273,984.83
SanDiego               89,791,919.69
Atlanta                88,605,118.85
Sacramento             75,163,746.86
Philadelphia           71,838,798.18
NorthernNewEngland     71,532,894.11
Tampa                  66,004,539.31
Detroit                63,422,419.38
SouthCarolina          60,753,772.90
Orlando                58,660,703.89
LasVegas               54,376,906.40
HartfordSpringfield    50,670,537.46
RaleighGreensboro      48,202,731.66
NewOrleansMobile       45,695,136.58
CincinnatiDayton       44,522,007.57
RichmondNorfolk        42,230,851.45
HarrisburgScranton     41,808,858.68
Nashville              35,612,089.23
Charlotte              35,555,544.42
StLouis                32,072,833.33
Indianapolis           30,263,391.43
GrandRapids            30,211,735.93
Columbus               29,993,361.42
Jacksonville           28,790,004.74
Roanoke                25,042,010.81
BuffaloRochester       22,962,470.40
Pittsburgh             18,806,345.81
Louisville             16,097,002.40
Albany                 16,067,799.97
Spokane                15,565,275.48
Boise                  14,413,187.75
Syracuse               10,942,667.68

(h) Calcule o volume total de abacates vendidos para cada tipo e ano.

In [107]:
df_avocado.groupby(['type','year'])[['total_volume']].sum()

total_volume
type         year                 
convencional 2015 1,405,835,526.60
             2016 1,538,913,526.12
             2017 1,505,463,914.14
             2018   433,710,441.83
orgânico     2015 1,322,377,914.02
             2016 1,462,817,222.93
             2017 1,564,148,221.75
             2018   425,395,644.21

(f) existe alguma região que foi a maior responsável pela queda na produção de 2018?

In [113]:
df_avocado.loc[df_avocado['year']==2018].groupby('region')[['total_volume']].sum().sort_values('total_volume').head(1)

total_volume
region                
Syracuse  1,046,987.66

(g) Qual cidade menos faturou com a venda de abacates?

In [116]:
df_avocado.groupby('region')[['total_volume']].sum().sort_values('total_volume',ascending=True).head(1)

total_volume
region                
Syracuse 10,942,667.68

### Problema 4

Com base no dataset 'Video_Games_Sales.csv' responda:


In [119]:
dfgames = pd.read_csv('data1/Video_Games_Sales.csv', sep=';')

dfgames

Name Platform  Year_of_Release         Genre  \
0                         Wii Sports      Wii         2,006.00        Sports   
1                  Super Mario Bros.      NES         1,985.00      Platform   
2                     Mario Kart Wii      Wii         2,008.00        Racing   
3                  Wii Sports Resort      Wii         2,009.00        Sports   
4           Pokemon Red/Pokemon Blue       GB         1,996.00  Role-Playing   
...                              ...      ...              ...           ...   
16714  Samurai Warriors: Sanada Maru      PS3         2,016.00        Action   
16715               LMA Manager 2007     X360         2,006.00        Sports   
16716        Haitaka no Psychedelica      PSV         2,016.00     Adventure   
16717               Spirits & Spells      GBA         2,003.00      Platform   
16718            Winning Post 8 2016      PSV         2,016.00    Simulation   

          Publisher  NA_Sales  EU_Sales  JP_Sales  Other_Sales  Global_Sales  \
0          Nintendo     41.36     28.96      3.77         8.45         82.53   
1          Nintendo     29.08      3.58      6.81         0.77         40.24   
2          Nintendo     15.68     12.76      3.79         3.29         35.52   
3          Nintendo     15.61     10.93      3.28         2.95         32.77   
4          Nintendo     11.27      8.89     10.22         1.00         31.37   
...             ...       ...       ...       ...          ...           ...   
16714    Tecmo Koei      0.00      0.00      0.01         0.00          0.01   
16715   Codemasters      0.00      0.01      0.00         0.00          0.01   
16716  Idea Factory      0.00      0.00      0.01         0.00          0.01   
16717       Wanadoo      0.01      0.00      0.00         0.00          0.01   
16718    Tecmo Koei      0.00      0.00      0.01         0.00          0.01   

       Critic_Score  Critic_Count  User_Score  User_Count Developer Rating  
0             76.00         51.00        8.00      322.00  Nintendo      E  
1               NaN           NaN         NaN         NaN       NaN    NaN  
2             82.00         73.00        8.30      709.00  Nintendo      E  
3             80.00         73.00        8.00      192.00  Nintendo      E  
4               NaN           NaN         NaN         NaN       NaN    NaN  
...             ...           ...         ...         ...       ...    ...  
16714           NaN           NaN         NaN         NaN       NaN    NaN  
16715           NaN           NaN         NaN         NaN       NaN    NaN  
16716           NaN           NaN         NaN         NaN       NaN    NaN  
16717           NaN           NaN         NaN         NaN       NaN    NaN  
16718           NaN           NaN         NaN         NaN       NaN    NaN  

[16719 rows x 16 columns]


(a) Quantos jogos existem em cada genero?


In [123]:
dfgames['Genre'].value_counts()

Action          3370
Sports          2348
Misc            1750
Role-Playing    1500
Shooter         1323
Adventure       1303
Racing          1249
Platform         888
Simulation       874
Fighting         849
Strategy         683
Puzzle           580
Name: Genre, dtype: int64

(b) Temos duplicados nesses dados? E nulos?

In [127]:
dfgames.isna().sum()

Name                  2
Platform              0
Year_of_Release     269
Genre                 2
Publisher            54
NA_Sales              0
EU_Sales              0
JP_Sales              0
Other_Sales           0
Global_Sales          0
Critic_Score       8582
Critic_Count       8582
User_Score         9129
User_Count         9129
Developer          6623
Rating             6769
dtype: int64

In [126]:
dfgames.duplicated().sum()

0

(b) Quantos jogos de cada publisher receberam nota acima de 9 na avaliação dos usuarios?

In [131]:
dfgames.loc[dfgames['User_Score']>9].groupby('Publisher')['Publisher'].count().sort_values()

Publisher
505 Games                              1
LucasArts                              1
Kemco                                  1
Kadokawa Shoten                        1
Jaleco                                 1
Interplay                              1
Infogrames                             1
Ignition Entertainment                 1
GT Interactive                         1
Square                                 1
Square Enix                            1
Destination Software, Inc              1
Codemasters                            1
Sting                                  1
Bethesda Softworks                     1
Sunflowers                             1
Telegames                              1
Activision Value                       1
ValuSoft                               1
Virgin Interactive                     1
Disney Interactive Studios             1
Metro 3D                               1
Microsoft Game Studios                 2
PQube                                  2
Marvel


(c) Faça uma tabela que mostre o total vendido por ano por pais/globalmente de cada publisher? Você consegue observar algum padrão? Com se comportaram as vendas na América do Norte (NA) ao longo do tempo? O mesmo foi visto nos demais lugares? 


In [138]:
dfgames.groupby(['Year_of_Release','Publisher'])[['Global_Sales','NA_Sales','EU_Sales','JP_Sales','Other_Sales']].sum()

Global_Sales  NA_Sales  \
Year_of_Release Publisher                                              
1,980.00        Activision                            3.02      2.82   
                Atari                                 8.36      7.77   
1,981.00        20th Century Fox Video Games          1.35      1.27   
                Activision                            8.50      7.95   
                Atari                                 8.45      7.87   
...                                                    ...       ...   
2,016.00        Yeti                                  0.02      0.00   
                dramatic create                       0.03      0.00   
2,017.00        Idea Factory                          0.01      0.00   
                Sega                                  0.05      0.00   
2,020.00        Ubisoft                               0.29      0.27   

                                              EU_Sales  JP_Sales  Other_Sales  
Year_of_Release Publisher                                                      
1,980.00        Activision                        0.18      0.00         0.03  
                Atari                             0.49      0.00         0.09  
1,981.00        20th Century Fox Video Games      0.07      0.00         0.01  
                Activision                        0.46      0.00         0.08  
                Atari                             0.47      0.00         0.08  
...                                                ...       ...          ...  
2,016.00        Yeti                              0.00      0.02         0.00  
                dramatic create                   0.00      0.03         0.00  
2,017.00        Idea Factory                      0.00      0.01         0.00  
                Sega                              0.00      0.05         0.00  
2,020.00        Ubisoft                           0.00      0.00         0.02  

[2337 rows x 5 columns]


(d) Qual foi jogo mais vendido na união européia? De que ano ele é e qual a editora?


In [141]:
dfgames.loc[dfgames['EU_Sales']==dfgames['EU_Sales'].max(),['Year_of_Release','Publisher','Name','EU_Sales']]

Year_of_Release Publisher        Name  EU_Sales
0         2,006.00  Nintendo  Wii Sports     28.96


(e) Quantos % os generos ['Racing', 'Sports', 'Shooter'] representam na base de dados? 

In [155]:
dfgames['Genre'].value_counts(normalize=True)

Action         0.20
Sports         0.14
Misc           0.10
Role-Playing   0.09
Shooter        0.08
Adventure      0.08
Racing         0.07
Platform       0.05
Simulation     0.05
Fighting       0.05
Strategy       0.04
Puzzle         0.03
Name: Genre, dtype: float64

(f) Qual plataforma vendeu menos globalmente? obs: imprimir somente o nome

In [161]:
list(dfgames.groupby('Platform')[['Global_Sales']].sum().sort_values('Global_Sales',ascending=True).head(1).index)[0]

'PCFX'

### Problema 5
A pasta 'data/datasus' contém informações sobre casos de dengue e tabelas auxiliares. <br>

| Tabela | Conteúdo |
|--------|----------|
| Dengue | Quantidade de casos por município |
| Agua | Quantidade de residências em cada município por tipo o abastecimento de água |
| InstalacoesSanitarias | Quantidade de residências em cada município por tipo de rede de esgoto |
| Pib | PIB per capita de cada município |
| Municipios | Relaciona o id_municipio com seu nome e estado |
| Populacao | Quantidade de pessoas morando em áreas urbanas, rurais e população total por município |
| Sexo | Quantidade de pessoas por sexo em cada município |

(a) Calcular o número de casos de dengue por cada estado apresentando os dados em ordem decrescente.


In [215]:
#filepaths = [f for f in os.listdir("./data1/datasus") if f.endswith('.csv')]
#filepaths = (['./data1/datasus/'+ f for f in filepaths])
dfdengue = pd.read_csv('./data1/datasus/Dengue.csv')
dfmun = pd.read_csv('./data1/datasus/Municipios.csv')

dfdengue = dfdengue.merge(dfmun, how='inner',on='id_municipio')

dfdengue.groupby('UF')[['casos']].sum().sort_values('casos',ascending=False)

casos
UF        
GO  274620
MG   15932
CE   11373
MT    7750
SP    5173
ES    5046
PA    4525
PI    3599
MA    3374
TO    3089
BA    2961
RJ    2658
PE    2151
MS    1678
RN    1418
RO    1324
AM    1237
PB     944
PR     818
AP     817
AC     777
AL     759
SE     334
RR     151
RS      45
SC      13

(b) Utilizando o dataset InstalacoesSanitarias.csv, determine o número de pessoas que não possuem meio sanitário algum de descarte de dejetos por estado.

In [216]:
dfsani = pd.read_csv('./data1/datasus/InstalacoesSanitarias.csv')

dfdengue = dfdengue.merge(dfsani, how='inner', on=['id_municipio','id_registro'])

dfdengue.groupby('UF')[['nao_possui']].sum()

nao_possui
UF            
RO    3,417.00

(c) Crie uma coluna com a posição de ranking considerando o PIB. Os maiores PIB devem ter os menores valores de ranking.

In [217]:
dfpib = pd.read_csv('./data1/datasus/Pib.csv')

dfmun = dfmun.merge(dfpib, how='inner',on='id_municipio')



id_municipio                       municipio  UF  id_registro  \
0                1    110001 Alta Floresta D'Oeste  RO            1   
1                2  110037 Alto Alegre dos Parecis  RO            2   
2                3             110040 Alto Paraíso  RO            3   
3                4         110034 Alvorada D'Oeste  RO            4   
4                5                110002 Ariquemes  RO            5   
...            ...                             ...  ..          ...   
5554          5562                   522170 Uruana  GO         5555   
5555          5563                   522180 Urutaí  GO         5556   
5556          5564      522185 Valparaíso de Goiás  GO         5557   
5557          5565                   522190 Varjão  GO         5558   
5558          5566               522200 Vianópolis  GO         5559   

      pib_percapta  
0        13,231.01  
1        13,222.71  
2        10,987.82  
3        10,993.43  
4        17,566.27  
...            ...  
5554     31,864.95  
5555     20,093.49  
5556     26,301.12  
5557     62,859.43  
5558     26,445.72  

[5559 rows x 5 columns]

In [226]:
dfmun = dfmun.sort_values('pib_percapta', ascending=False)
dfmun['Ranking'] = list(range(1,len(dfmun)+1))
dfmun

id_municipio                   municipio  UF  id_registro  pib_percapta  \
3152          3155           320425 Ponto Belo  ES         3153    715,193.70   
2962          2965  316180 São Gonçalo do Pará  MG         2963    340,688.49   
3574          3577              352725 Lourdes  SP         3575    278,145.26   
3230          3233          330410 Porciúncula  RJ         3231    255,658.30   
5163          5169            500730 Rio Negro  MS         5164    254,242.69   
...            ...                         ...  ..          ...           ...   
617            618  211023 Santana do Maranhão  MA          618      3,566.34   
2106          2109       292303 Novo Horizonte  BA         2107      3,561.71   
563            564              210650 Matinha  MA          564      3,529.10   
643            644   211170 São Vicente Ferrer  MA          644      3,510.69   
572            573               210710 Morros  MA          573      3,241.29   

      Ranking  
3152        1  
2962        2  
3574        3  
3230        4  
5163        5  
...       ...  
617      5555  
2106     5556  
563      5557  
643      5558  
572      5559  

[5559 rows x 6 columns]

(d) Qual o PIB dos 5 municípios com mais casos de dengue e sua posição no ranking?

In [227]:
dfdengue = pd.read_csv('./data1/datasus/Dengue.csv')

dfdengue = dfdengue.merge(dfmun, how='inner', on='id_municipio')



In [236]:
dfdengue.sort_values('casos',ascending=False)[['municipio','casos','pib_percapta','Ranking']].head(5)

municipio   casos  pib_percapta  Ranking
2455           522200 Vianópolis  239395     26,445.72      905
2283  520085 Americano do Brasil   10859     19,774.03     1572
2337              520810 Formoso    9340     29,034.21      742
499             230435 Forquilha    4321     19,494.40     1602
2192              510325 Colniza    3298     31,016.19      641